### ISSUE TITLE
Why deleted from Steam workshop?

### ISSUE THREAD

**Issue by iUltimateLP** [Fr0sZ/Skylines-Multiplayer#1]
I liked this mod, but why is it not available anymore?
Thanks :)

**Comment by MollerVictor** [comment]
Hey, sorry about that. But I couldn't put the time in to keep it updated
with all the new dlcs and updates, and in it's current state it was broken.

2016-03-06 10:01 GMT+01:00 Johnny notifications@github.com:

**Comment by iUltimateLP** [comment]
Well, maybe I could try to do something :joy: I already made one mod for C:S which was an Autosave Countdown, and my knowledge about Netcode stuff isn't the best, but I could try.. One question, the whole thing is running through an "api" server which is on your domain.. Will you keep that on?

**Comment by MollerVictor** [comment]
Yeah the server that handles the master server will stay up. You are
welcome to try to do something, if you can read my mess of code :P. Not
completely sure what things are broken currently. I know that the menu
seemed to be bugged again, and the night and day cycle isn't synced. I
actually have writing code for vehicles also, but haven't pushed those
because they are pretty performance heavy and also because of the way they
raycast roads, the above ground roads are a bit off, which is annoying.

2016-03-06 14:47 GMT+01:00 Johnny notifications@github.com:

**Comment by iUltimateLP** [comment]
Yeah, I recognized the syncing stuff also when I was toying around with friends. One question: Is it possible to make a game like "Both build a city together"? I mean, technicially, we would need to catch the events when one builds an building, and that event needs to be replicated to all clients connected, and vice versa.. Would that be too hard?

**Comment by MollerVictor** [comment]
Nah the problem is that the simulation are gonna get desynced, the way to
game is coded it's to many things that gonna give you 2 different results
even you do the same thing. Like it might be possible to fake it, but that
requires way to much work.

2016-03-06 15:21 GMT+01:00 Johnny notifications@github.com:

**Comment by iUltimateLP** [comment]
Oh, they should have implemented that from Day One on...
